version: "3.8"
name: rated-assessment
volumes:
  pgdata: null

networks:
  postgres-db-network:
      driver: bridge
services:
  app:
    image: rated-assessment
    restart: always
    environment: &env
      DATABASE_URL: postgresql+psycopg://rated:rated@db:5432/rated
      LOGS_SOURCE_DIR: /data/logs
    ports:
      - "8888:8888"
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      db-migration:
        condition: service_completed_successfully

  db:
    image: postgres:17-alpine
    restart: always
    environment:
      POSTGRES_USER: rated
      POSTGRES_PASSWORD: rated
      POSTGRES_DB: rated
      POSTGRES_HOST_AUTH_METHOD: trust
    healthcheck:
      test: "pg_isready --username=rated"
      interval: 2s
      timeout: 3s
      retries: 3
    expose:
      - 5432
    volumes:
      - pgdata:/var/lib/postgresql/data

  db-migration:
    image: rated-assessment
    environment: *env
    depends_on:
      db:
        condition: service_healthy
    restart: "no"
    entrypoint: [ "bash", "-c", "python -m scripts.init_schema"]

  bytewax:
    image: rated-assessment
    environment: *env
    depends_on:
      db-migration:
        condition: service_completed_successfully
    restart: "no"
    entrypoint: [ "bash", "-c", "python -m bytewax.run ingest/log_parser.py" ]
    volumes:
      - ./logs:/data/logs