"""init

Revision ID: efb217d0ebad
Revises: 
Create Date: 2024-10-04 20:07:23.889778

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel             # NEW


# revision identifiers, used by Alembic.
revision = 'efb217d0ebad'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('resource_statistics_by_day',
    sa.Column('dt', sa.Date(), nullable=False),
    sa.Column('customer_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('request_path', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('status_code', sa.Integer(), nullable=True),
    sa.Column('duration_p50', sa.Float(), nullable=False),
    sa.Column('duration_p90', sa.Float(), nullable=False),
    sa.Column('duration_p95', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('dt', 'customer_id', 'request_path', 'status_code')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('resource_statistics_by_day')
    # ### end Alembic commands ###